export enum ActionType
{
    Delete=1,
    Create=2,
    Update=3,
    Inc=4,
    UpdateManySet=5,
    UpdateManyInc=6, 
    DeleteMany=7,
    DeleteOne=8,
}
export default class ActionModel
{
    model:any;
    action:ActionType
    data:any
    include:any
    condition:any
    constructor(data:{
        model:any;
        action:ActionType
        data?:any
        include?:any
        condition?:any
    })
    {
        Object.assign(this,data)
    }
}